### ISSUE TITLE
Лабораторная работа №2

### ISSUE THREAD

**Issue by iskochegarov** [iskochegarov/lab2#1]
Выполнил Кочегаров Илья
гр. ИВ-522

To: @evgeny-p

**Comment by evgeny-p** [comment]
1. Неконсистентное форматирование в файле `roots.c`: пробелы внутри скобок и вокруг бинарных операторов.

1. Нетипичное форматирование условного оператора в файле `main.c` (перенос строки между `else` и `if` с дополнительным уровнем вложенности), см. гайды [раз](https://www.kernel.org/doc/Documentation/CodingStyle), [два](https://google.github.io/styleguide/cppguide.html#Conditionals).

**Comment by iskochegarov** [comment]
Готово! (Если я всё правильно понял)

**Comment by evgeny-p** [comment]
Принято.
